all: clean yeast-genome chromesome-feature palinsreg 

yeast-genome:
	./yeast_genome.sh

chromesome-feature:
	./chromesome_feature.sh

palinsreg:
	./palinsreg.sh

clean:
	find . -name *.tmp -exec rm {} \;
